'use client'

import { useState } from 'react'
import { ArrowRight, Check, Clock3, Factory, MapPin, Menu, MessageCircle, ShieldCheck, Sparkles, AtSign, X } from 'lucide-react'

const whatsapp = 'https://wa.me/5548999491115?text=Ol%C3%A1!%20Vim%20pelo%20site%20da%20Aleeds%20e%20gostaria%20de%20solicitar%20um%20or%C3%A7amento.'
const services = ['Janelas de alumínio','Portas de alumínio','Portas de vidro','Box para banheiro','Guarda-corpo','Fachadas','Portões','Coberturas de vidro','Pele de vidro','Fechamento de sacadas','Corrimão']
const cities = ['Urussanga','Criciúma','Içara','Morro da Fumaça','Orleans','Tubarão','Laguna','Imbituba','Garopaba','Florianópolis','São José','Biguaçu','Tijucas','Porto Belo','Itapema','Passo de Torres']
const gallery = ['Esquadrias','Fachadas','Portões','Box','Coberturas','Vidros','Residencial','Comercial']

function Placeholder({ label, className = '' }: { label: string; className?: string }) {
  return <div className={`flex min-h-48 items-center justify-center bg-primary/5 text-center ${className}`}><div><Factory className="mx-auto mb-3 size-8 text-accent" strokeWidth={1.4} /><span className="font-mono text-xs uppercase tracking-[0.22em] text-muted-foreground">{label}</span></div></div>
}

export function AleedsLanding() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [lightbox, setLightbox] = useState<string | null>(null)
  const nav = [['Início','#inicio'],['Serviços','#servicos'],['Nossos trabalhos','#trabalhos'],['Sobre nós','#sobre'],['Contato','#contato']]
  return <div className="min-h-screen bg-background">
    <header className="sticky top-0 z-40 border-b border-border/70 bg-background/95 backdrop-blur">
      <div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8">
        <a href="#inicio" className="leading-none" aria-label="Aleeds, início"><span className="block text-xl font-black tracking-[0.18em] text-primary">ALEEDS</span><span className="mt-1 block text-[9px] font-medium uppercase tracking-[0.2em] text-muted-foreground">Alumínio e vidro temperado</span></a>
        <nav className="hidden items-center gap-7 lg:flex">{nav.map(([label,href]) => <a key={href} href={href} className="text-sm text-muted-foreground transition-colors hover:text-primary">{label}</a>)}<a href={whatsapp} target="_blank" rel="noreferrer" className="rounded-md bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground transition-transform hover:-translate-y-0.5">Solicitar orçamento</a></nav>
        <button className="rounded-md p-2 lg:hidden" aria-label={menuOpen ? 'Fechar menu' : 'Abrir menu'} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button>
      </div>
      {menuOpen && <nav className="flex flex-col gap-1 border-t px-5 py-4 lg:hidden">{nav.map(([label,href]) => <a key={href} href={href} onClick={() => setMenuOpen(false)} className="py-3 text-sm text-muted-foreground">{label}</a>)}<a href={whatsapp} target="_blank" rel="noreferrer" className="mt-2 rounded-md bg-primary px-4 py-3 text-center text-sm font-semibold text-primary-foreground">Solicitar orçamento</a></nav>}
    </header>
    <main>
      <section id="inicio" className="mx-auto grid max-w-7xl gap-10 px-5 pb-20 pt-14 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8 lg:pb-28 lg:pt-24">
        <div><p className="mb-6 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.22em] text-accent"><span className="h-px w-8 bg-accent" /> Urussanga · Santa Catarina</p><h1 className="max-w-3xl text-balance text-4xl font-bold leading-[1.08] tracking-tight text-primary sm:text-6xl">Esquadrias de Alumínio e Vidro Temperado em Santa Catarina</h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted-foreground">Fabricação própria, projetos sob medida e mais de 15 anos de experiência.</p><p className="mt-2 max-w-xl leading-7 text-muted-foreground">Atendemos residências, empresas e obras de Passo de Torres a Itapema.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href={whatsapp} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-md bg-primary px-6 py-4 font-semibold text-primary-foreground">Solicitar orçamento pelo WhatsApp <ArrowRight data-icon="inline-end" /></a><a href="#trabalhos" className="inline-flex items-center justify-center rounded-md border border-primary/20 px-6 py-4 font-semibold text-primary">Conheça nossos trabalhos</a></div><div className="mt-12 grid grid-cols-3 gap-4 border-t pt-6"><div><strong className="block text-lg text-primary">Desde 2011</strong><span className="text-xs text-muted-foreground">Experiência</span></div><div><strong className="block text-lg text-primary">Própria</strong><span className="text-xs text-muted-foreground">Fabricação</span></div><div><strong className="block text-lg text-primary">1 ano</strong><span className="text-xs text-muted-foreground">Garantia</span></div></div></div>
        <Placeholder label="Trocar por foto de obra / hero.jpg" className="min-h-[420px] rounded-sm lg:min-h-[560px]" />
      </section>
      <section id="sobre" className="bg-secondary/55"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><p className="eyebrow">Quem somos</p><h2 className="section-title">Qualidade do projeto à instalação</h2></div><div><p className="lead">Desde 2011, a Aleeds Alumínio e Vidro Temperado desenvolve soluções sob medida em esquadrias de alumínio e vidro temperado.</p><p className="mt-5 leading-7 text-muted-foreground">Contamos com fabricação própria em Urussanga, equipe experiente e atendimento personalizado, acompanhando cada projeto desde as medidas até a instalação final.</p><p className="mt-5 leading-7 text-muted-foreground">Nosso compromisso é entregar produtos com qualidade, acabamento, resistência e durabilidade para cada obra.</p><div className="mt-10 grid gap-4 sm:grid-cols-2">{[['+15 anos','Experiência acumulada desde 2011 em projetos residenciais e comerciais.'],['Fabricação própria','Produção realizada na própria Aleeds, com maior controle de qualidade.'],['1 ano de garantia','Mais segurança e tranquilidade após a instalação.'],['Atendimento personalizado','Cada projeto é desenvolvido conforme a necessidade do cliente.']].map(([t,d]) => <div key={t} className="border-t border-border pt-4"><strong className="text-primary">{t}</strong><p className="mt-2 text-sm leading-6 text-muted-foreground">{d}</p></div>)}</div></div></div></section>
      <section id="servicos" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><p className="eyebrow">Nossas soluções</p><h2 className="section-title max-w-xl">Soluções em alumínio e vidro para sua obra</h2><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{services.map((s,i) => <article key={s} className="overflow-hidden rounded-sm border bg-card"><Placeholder label={`Imagem ${s}`} className="min-h-40" /><div className="p-5"><h3 className="text-lg font-semibold text-primary">{s}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Soluções sob medida que combinam resistência, acabamento e funcionalidade.</p><a href={whatsapp} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-accent">Solicitar orçamento <ArrowRight data-icon="inline-end" /></a></div></article>)}</div></section>
      <section className="bg-primary text-primary-foreground"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><p className="eyebrow text-primary-foreground/70">Fabricação própria</p><h2 className="section-title text-primary-foreground">Do projeto à fabricação</h2><p className="mt-5 leading-7 text-primary-foreground/75">Na Aleeds, grande parte do processo acontece dentro da própria empresa. Nossa fabricação própria permite maior controle de qualidade, precisão nas medidas e personalização dos projetos.</p></div><div className="grid gap-4 sm:grid-cols-3"><Placeholder label="Fabricação" className="min-h-52 bg-primary-foreground/10 text-primary-foreground" /><Placeholder label="Produção" className="min-h-52 bg-primary-foreground/10 text-primary-foreground" /><Placeholder label="Acabamento" className="min-h-52 bg-primary-foreground/10 text-primary-foreground" /></div></div></section>
      <section id="trabalhos" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><p className="eyebrow">Portfólio</p><h2 className="section-title">Veja a transformação</h2><div className="mt-10 grid gap-6 lg:grid-cols-3">{['Residência em Criciúma','Fachada comercial em Urussanga','Fechamento de sacada em Itapema'].map((t) => <article key={t} className="border bg-card p-3"><div className="grid grid-cols-2 gap-2"><Placeholder label="Antes" className="min-h-36" /><Placeholder label="Depois" className="min-h-36" /></div><div className="p-3"><h3 className="font-semibold text-primary">{t}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Projeto sob medida, com acompanhamento da equipe Aleeds.</p></div></article>)}</div><a href="#galeria" className="mt-8 inline-flex rounded-md border border-primary/20 px-5 py-3 text-sm font-semibold text-primary">Ver mais trabalhos</a></section>
      <section id="galeria" className="bg-secondary/55"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><p className="eyebrow">Galeria</p><h2 className="section-title">Projetos que levam a qualidade Aleeds</h2><div className="mt-10 grid grid-cols-2 gap-3 md:grid-cols-4">{gallery.map((g,i) => <button key={g} onClick={() => setLightbox(g)} className={`text-left ${i===0 || i===5 ? 'md:col-span-2' : ''}`} aria-label={`Abrir imagem de ${g}`}><Placeholder label={g} className="min-h-44 transition-colors hover:bg-primary/10" /></button>)}</div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">{[['Experiência','Desde 2011 trabalhando com alumínio e vidro temperado.',Clock3],['Fabricação própria','Produção realizada na própria Aleeds.',Factory],['Projetos sob medida','Soluções desenvolvidas para cada projeto.',Sparkles],['Materiais de qualidade','Resistência, acabamento e durabilidade.',ShieldCheck],['Atendimento personalizado','Acompanhamento até a instalação.',MessageCircle],['Garantia','Nossos serviços possuem garantia de 1 ano.',Check]].map(([t,d,Icon]) => <div key={t as string} className="flex gap-4"><div className="flex size-10 shrink-0 items-center justify-center rounded-full bg-primary/5 text-accent"><Icon /></div><div><h3 className="font-semibold text-primary">{t as string}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{d as string}</p></div></div>)}</div></section>
      <section className="bg-secondary/55"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><p className="eyebrow">Onde estamos</p><h2 className="section-title">Atendemos do Sul ao Litoral de Santa Catarina</h2><p className="mt-5 leading-7 text-muted-foreground">A Aleeds está localizada em Urussanga - SC e atende projetos em diversas cidades, de Passo de Torres a Itapema.</p></div><div className="flex flex-wrap content-start gap-2">{cities.map(c => <span key={c} className="rounded-full border bg-background px-4 py-2 text-sm text-muted-foreground">{c}</span>)}</div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="rounded-sm bg-primary px-6 py-12 text-center text-primary-foreground sm:px-12"><h2 className="text-3xl font-bold tracking-tight">Pensando em construir ou reformar?</h2><p className="mx-auto mt-4 max-w-xl text-primary-foreground/75">Solicite seu orçamento diretamente com nossa equipe. Atendimento personalizado para projetos residenciais e comerciais.</p><a href={whatsapp} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 rounded-md bg-background px-6 py-4 font-semibold text-primary">Solicitar orçamento pelo WhatsApp <ArrowRight data-icon="inline-end" /></a></div></section>
      <section id="contato" className="border-t"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><p className="eyebrow">Contato</p><h2 className="section-title">Fale com a Aleeds</h2><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[['WhatsApp','(48) 99949-1115',MessageCircle],['Instagram','@aleedsaluminio',AtSign],['Endereço','Rodovia Genézio Mazon, 2297 · De Villa · Urussanga - SC',MapPin],['Horário','Segunda a sexta-feira · 7:30 às 17:20',Clock3]].map(([t,d,Icon]) => <div key={t as string} className="border p-5"><Icon className="mb-5 text-accent" /><h3 className="font-semibold text-primary">{t as string}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{d as string}</p>{t === 'WhatsApp' && <a href={whatsapp} target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm font-semibold text-accent">Chamar no WhatsApp</a>}{t === 'Instagram' && <a href="https://instagram.com/aleedsaluminio" target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm font-semibold text-accent">Visitar Instagram</a>}</div>)}</div><div className="mt-10 flex flex-wrap items-center gap-4 border-y py-6"><strong className="text-primary">Facilidade no pagamento</strong>{['Pix','Dinheiro','Cartão','Boleto'].map(p => <span key={p} className="inline-flex items-center gap-2 text-sm text-muted-foreground"><Check className="size-4 text-accent" /> {p}</span>)}</div><div className="mt-8 flex min-h-32 items-center justify-center border bg-secondary/50 text-sm text-muted-foreground">Espaço reservado para mapa do Google Maps</div></div></section>
    </main>
    <footer className="bg-primary text-primary-foreground"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-5 py-12 lg:flex-row lg:items-end lg:justify-between lg:px-8"><div><span className="text-xl font-black tracking-[0.18em]">ALEEDS</span><p className="mt-3 max-w-sm text-sm leading-6 text-primary-foreground/70">Esquadrias de alumínio e vidro temperado desde 2011.<br />Rodovia Genézio Mazon, 2297, De Villa, Urussanga - SC</p></div><div className="flex flex-wrap gap-x-5 gap-y-3 text-sm text-primary-foreground/75">{nav.map(([l,h]) => <a key={h} href={h}>{l}</a>)}<a href="https://instagram.com/aleedsaluminio">Instagram</a><a href={whatsapp}>WhatsApp</a></div><p className="text-xs text-primary-foreground/55">© 2026 Aleeds Alumínio e Vidro Temperado. Todos os direitos reservados.</p></div></footer>
    <a href={whatsapp} target="_blank" rel="noreferrer" aria-label="Falar com a Aleeds pelo WhatsApp" className="fixed bottom-5 right-5 z-30 flex size-14 items-center justify-center rounded-full bg-accent text-accent-foreground shadow-lg"><MessageCircle /></a>
    {lightbox && <div className="fixed inset-0 z-50 flex items-center justify-center bg-primary/80 p-5" role="dialog" aria-modal="true" aria-label={`Imagem de ${lightbox}`} onClick={() => setLightbox(null)}><div className="w-full max-w-2xl" onClick={e => e.stopPropagation()}><Placeholder label={`Imagem real: ${lightbox}`} className="min-h-[60vh] bg-background" /><button onClick={() => setLightbox(null)} className="mx-auto mt-4 block rounded-md bg-background px-5 py-3 text-sm font-semibold text-primary">Fechar</button></div></div>}
  </div>
}
